### ISSUE TITLE
band 8A has incorrect file name

### ISSUE THREAD

**Issue by mamiekus** [sat-utils/sat-stac-sentinel#11]
Hi, 
https://github.com/sat-utils/sat-stac-sentinel/blob/2ffbcc8e47cec32809e9661995c6e157b034fb26/satstac/sentinel/main.py#L176
I think there is a mistake, the band 8A file is not B08.jp2 but B8A.jp2.

--
thanks
MM

**Comment by vincentsarago** [comment]
Thanks @mamiekus for opening the issue! 

@matthewhanson I'll be happy to fix this one 😄
